name: robotframework-cicd-poc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependecies
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: install -d # Install all dependencies, including development ones
    - name: Lint
      run: |
        pylint ./robotframework-cicd-poc  
    - name: Test
      uses: VaultVulp/action-pipenv@v2.0.1
      with:
        command: run test # Run custom `test` command defined in the `[scripts]` block of Pipfile
