name: robotframework-cicd-poc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Setup Environment
      run: |
         python -m pip install --upgrade pip
         pip install -U pipenv
         pipenv install
    - name: Lint
      run: |
        pipenv run pylint ./app  
    - name: Test
      run: |
        pipenv run webdrivermanager chrome
        pipenv run robot -d ./app/tests/results/ --loglevel TRACE ./app/tests/GoogleTest.robot
        pipenv run robotmetrics -M metrics.html --inputpath ./app/tests/results/ --output output.xml
    - name: html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: ./app/tests/results/metrics.html
        outputFile: ./app/tests/results/metrics.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Robot Framework Test Result
        to: ${{secrets.MAIL_USERNAME}}
        from: ${{secrets.MAIL_USERNAME}}
        secure: true
        body: Build job of ${{github.repository}} completed successfully!
        html_body: ./app/tests/results/metrics.html
        reply_to: ${{secrets.MAIL_USERNAME}}
        in_reply_to: ${{secrets.MAIL_USERNAME}}
        ignore_cert: true
        convert_markdown: true
        attachments: ./app/tests/results/metrics.pdf
        priority: low
